sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build app
  - docker-compose build app-tests-with-report

script:
  - >
    docker-compose run
    --rm
    -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN
    app-tests-with-report

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack:
    secure: BaxJ52p3bvIuNXBYol/c5wYKZAFbqesBt6eQj0xqgvVs6c6w8hPkXk7Oxy1yjKjXHva249KNGCGqZSHp6SYwjkatrFI+rQynrDf7yJB8tvlgsN4az4HOz+65UdUGbX9JDvT4g1YamJf3lktCDQbHXmaW2Pb8qDbPTKZEe+2zYyATTesxRom3GimaE+PqVgUNzudNTgzGDv6hvH5K82ixLWIpidB8ySE+oKDioC05JTbvgYd/jff5iuFT5taKWlzvpmGgeFbu5Dd2t90Nfzg4NaGP9+vAcXDsoRaRXiAowPcP9A6N8SERciyW6ZZcIIVEv9E67nJxbsFpnCzHe5U79KVtKaG9rOTfCRTE3+LOJn6Aq/2xBGeGi9hSTYG9yB1djsBOljRRByp+bv+WiApa+JCD6cJtynJzSSyINr87+z2mK01tD1SDblQTkUTF5Ps84i+l4aj8mJ7ZbMNPC3/8Q4BWm5ngLkZlhMDSzmTBWmqSB5AQc1duYquWMftAk8vxmBaW20HdKcUG3ECzP6LDz7myQXrqf/Pcpa9LodHtyu1rPAF2T5sakLNcMlfvWhWWdPI5U70V+CP8pdBJhs3TeNPNCojIOSMPY5h2SRfl/TbgGOLq859Cz4ss8QQot09lN9/QtrD6ddBsD6QBxfCmAwm+vPfmL30/uyvHN2mox3Y=
