version: "2"

services:

  app:
    build: .
    image: keboola/dynamodb-extractor
    tty: true
    stdin_open: true
    links:
      - dynamodb
    command: bash
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  app-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    links:
      - dynamodb
    command: sh -c 'php ./loadSampleData.php && ./tests.sh'

  app-tests-with-report:
    build:
      context: .
      dockerfile: Dockerfile-tests
    links:
      - dynamodb
    command: >
             sh -c '
             php ./loadSampleData.php
             && ./tests.sh
             && ./vendor/bin/test-reporter
             '
    volumes:
      - ./.git:/code/.git

  dynamodb:
    image: quay.io/keboola/dynamodb-extractor-dynamodb
