version: "3.8"

services:

  app:
    build: .
    image: keboola/dynamodb-extractor
    tty: true
    stdin_open: true
    links:
      - dynamodb
    command: bash
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  app-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    links:
      - dynamodb
    command: sh -c 'wait-for-it -t 100 dynamodb:8000 && php ./init.php && ./tests.sh'

  dynamodb:
    image: amazon/dynamodb-local:1.18.0
    ports:
      - '8000:8000'

