version: "2"

services:

  app:
    build: .
    image: keboola/dynamodb-extractor
    tty: true
    stdin_open: true
    links:
      - dynamodb
    command: bash
    volumes:
      - ./:/code

  app-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    links:
      - dynamodb
    command: sh -c './tests.sh'

  dynamodb:
    image: quay.io/keboola/dynamodb-extractor-dynamodb
